version: "3.8"
services:
  app:
    build: .
    ports:
      - "7866:7867"         # host:container
    volumes:
      - .:/app
    working_dir: /app
    command: uvicorn webapp.backend.main:app --host 0.0.0.0 --port 7867 --reload --reload-dir /app/webapp
