FROM paddlepaddle/paddle:3.2.0

WORKDIR /app
# Copy application code
COPY . .

RUN pip install paddleocr
RUN pip install fastapi uvicorn av aiortc python-multipart
RUN pip install ultralytics easydict onnx onnxruntime protobuf filterpy
RUN pip install opencv-python scikit-learn scikit-image matplotlib tqdm pandas seaborn shapely pyclipper imgaug
# Expose port for web application
EXPOSE 7864

# Default command runs the FastAPI web app
CMD ["uvicorn", "scripts.parking_services:app", "--host", "0.0.0.0", "--port", "7864"]